version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - vendor_volume:/app/vendor
    environment:
      APP_ENV: '${APP_ENV}'

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/app
    ports:
      - "8000:80"

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: '${DB_NAME:-converter}'
      MYSQL_USER: '${DB_USERNAME:-symfony}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-symfony}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-root}'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: {}
  vendor_volume: {}
